ID-B-4.1
grigarian/PetFamily pull request #5
Opened 2024-08-21 20:03 UTC by grigarian

2024-08-21 21:02 UTC, YaraOduvanchik requested changes

2024-08-21 21:02 UTC, n-cherashev commented on backend/src/PetFamily.Infrastructure/ApplicationDbContext.cs
> +            optionsBuilder.UseNpgsql(configuration.GetConnectionString(DATABASE));
Ты забыл добавить метод UseCamelCaseNamingConvention

2024-08-21 21:02 UTC, YaraOduvanchik commented on backend/src/PetFamily.Infrastructure/Configuration/PetConfiguration.cs
> +            builder.OwnsOne(p => p.PetStatus, pb =>
Тут можно сделать подругому, ненужно использовать много OwnsOne, лучше используй ComplexProperty

2024-08-23 08:50 UTC, grigarian commented on backend/src/PetFamily.Infrastructure/Configuration/PetConfiguration.cs
> +            builder.OwnsOne(p => p.PetStatus, pb =>
У меня PetStatus в изначальном виде лежит как enum, и если я его не конвертирую в стринг, то ef не дает сделать миграцию, а у ComplexProperty я не могу понять как сделать конвертацию

2024-08-23 08:53 UTC, YaraOduvanchik commented on backend/src/PetFamily.Infrastructure/Configuration/PetConfiguration.cs
> +            builder.OwnsOne(p => p.PetStatus, pb =>
Хорошо, тогда оставь так пока что

2024-08-23 08:54 UTC, YaraOduvanchik approved these changes

2024-08-23 08:55 UTC, merged